# MATH 189 Project: Cleaned Datasets and Spatial Merge

This notebook prepares and merges datasets for statistical analysis of transportation noise and socioeconomic inequality in Southern California.

We focus on tract-level analysis using transportation noise exposure, demographic variables, and environmental indicators.

## Workflow Overview

1. Load raw datasets
2. Clean variables and GEOIDs
3. Standardize tract identifiers
4. Merge datasets
5. Handle missing values
6. Export final analysis dataset

## Imports

In [43]:
# Imports

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import os

## Load Transportation Noise Data

This dataset contains transportation-related noise exposure measurements by census tract.

In [25]:
# Load transportation noise data

noise = pd.read_csv(
    '../data/processed/tract/sd_tract_noise.csv'
)

# Preview first rows
noise.head()

        GEOID    NAME  mean_noise  max_noise  min_noise
0  6073008331   83.31   56.328147  81.841232  45.003738
1  6073008336   83.36   52.557514  60.831444  45.011963
2  6073008337   83.37   58.447012  81.628632  45.016068
3  6073011601  116.01   51.534390  59.524536  45.223137
4  6073011602  116.02   55.575460  82.591164  45.002365

In [27]:
# Check dataset dimensions

print(noise.shape)

(737, 5)

In [29]:
# Check column names

print(noise.columns)

Index(['GEOID', 'NAME', 'mean_noise', 'max_noise', 'min_noise'], dtype='str')

In [31]:
# Check data types

noise.dtypes

GEOID           int64
NAME          float64
mean_noise    float64
max_noise     float64
min_noise     float64
dtype: object

In [33]:
# Check missing values

noise.isna().sum()

GEOID         0
NAME          0
mean_noise    3
max_noise     3
min_noise     3
dtype: int64

In [35]:
# Standardize tract identifiers

noise['GEOID'] = noise['GEOID'].astype(str)

In [37]:
# Rename columns for consistency

noise = noise.rename(columns={
    'GEOID': 'tract_id',
    'NAME': 'tract_name',
    'mean_noise': 'noise_mean_db',
    'max_noise': 'noise_max_db',
    'min_noise': 'noise_min_db'
})

noise.head()

     tract_id  tract_name  noise_mean_db  noise_max_db  noise_min_db
0  6073008331       83.31      56.328147     81.841232     45.003738
1  6073008336       83.36      52.557514     60.831444     45.011963
2  6073008337       83.37      58.447012     81.628632     45.016068
3  6073011601      116.01      51.534390     59.524536     45.223137
4  6073011602      116.02      55.575460     82.591164     45.002365

In [41]:
# Save cleaned transportation noise dataset

noise.to_csv(
    '../data/processed/tract/tract_noise.csv',
    index=False
)